// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvwicodeoopzzclhdwpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2d2ljb2Rlb29wenpjbGhkd3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjQ4OTksImV4cCI6MjA1OTUwMDg5OX0.hULyWrFfzRKW3XOOlCSlkO8BxiTgTltgzzXmIoldFw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);